main.c: use _() instead of gettext()
Use the _ shortcut to honour --disable-nls. Fixes

main.c: In function ‘show_status’:
main.c:692:19: warning: implicit declaration of function ‘gettext’ [-Wimplicit-function-declaration]
   show_status_fmt(gettext(statusline_format));

Signed-off-by: Rasmus Villemoes <rasmus.villemoes@prevas.dk>